title: <p align="center"> Indraneel Pradhan </p>
logo: /assets/img/indraneel_pic.JPG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/indraneel-prad/">LinkedIn</a> |
  <a href="https://github.com/indraneelpradhan1997">GitHub</a>
  
  <br>   
  I'm working React js, Java 8, Spring boot.
  Working in Healthcare domain for 4 years.
  <br>
  </p>



theme: jekyll-theme-minimal
